### ISSUE TITLE
Why are the no transistors and one diode in transmitter CPL?

### ISSUE THREAD

**Issue by nm17** [whoim2/qczek-E32xxxTy0s-pcb#1]

**Comment by whoim2** [comment]
Добрый!dtc144/bcr533 или любые digital npn sot23, диод шоттки любой на 1А или выше в sod-123. Вроде я на странице оставил ссылки на али с названиями компонентов, гляньте.@whoim220 дек. 2020 г. 18:25 пользователь Даниил Николаев <notifications@github.com> написал:

**Comment by nm17** [comment]
> Добрый!dtc144/bcr533 или любые digital npn sot23, диод шоттки любой на 1А или выше в sod-123. Вроде я на странице оставил ссылки на али с названиями компонентов, гляньте.

@whoim2 Мне нужно именно в формате CPL/BOM, т.е в файлах `*_bom.csv` и `*_pp.xls` для передатчика и очень желательно для приёмника

**Comment by whoim2** [comment]
Выгрузите их из диптрейс, исходники есть на гитхабе. Я не выгружал, а точнее удалил из из бом и пп, поскольку у jlcpcb они в extended parts и ценник невменяемый.@whoim220 дек. 2020 г. 19:28 пользователь Даниил Николаев <notifications@github.com> написал:

Добрый!dtc144/bcr533 или любые digital npn sot23, диод шоттки любой на 1А или выше в sod-123. Вроде я на странице оставил ссылки на али с названиями компонентов, гляньте.

@whoim2 Мне нужно именно в формате CPL/BOM, т.е в файлах *_bom.csv и *_pp.xls для передатчика и очень желательно для приёмника
