### ISSUE TITLE
really nice to see it!!

### ISSUE THREAD

**Issue by krzysztofkuczek** [whoim2/qczek-E32xxxTy0s-pcb#2]
Maybe you can make version compatible with 32 bit stm L0 mcu ? Or maybe event something really small and unique stm32wle5 with embeded lora chip…?
Kris

**Comment by whoim2** [comment]
Maybe. You have new firmwares for new modules?@whoim23 янв. 2021 г. 11:11 пользователь Krzysztof Kuczek <notifications@github.com> написал:

Maybe you can make version compatible with 32 bit stm L0 mcu ? Or maybe event something really small and unique stm32wle5 with embeded lora chip…?

Kris

**Comment by krzysztofkuczek** [comment]
I don't have, but if i would have hardware, i would be able to create new 32 bit firmware for it.
kris

**Comment by whoim2** [comment]
Ebyte have modules with sx chip and 32bit mcu?@whoim210 янв. 2021 г. 16:43 пользователь Krzysztof Kuczek <notifications@github.com> написал:
I don't have, but if i would have hardware, i would be able to create new 32 bit firmware for it.
kris
